"""add_revenuecat_tables

Revision ID: 4ccf985bc098
Revises: 20260513_0009
Create Date: 2026-06-17 11:28:53.871094
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4ccf985bc098'
down_revision = '20260513_0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenuecat_webhook_events',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('app_user_id', sa.String(length=255), nullable=False),
    sa.Column('original_app_user_id', sa.String(length=255), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('store', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('ix_timelines_plant_id'), table_name='timelines')
    op.drop_index(op.f('ix_timelines_user_id'), table_name='timelines')
    op.drop_table('timelines')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.alter_column('action_types', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Unique action type identifier.',
               existing_nullable=False)
    op.alter_column('action_types', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('action_types', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='Action type name.',
               existing_nullable=False)
    op.alter_column('action_types', 'icon',
               existing_type=sa.VARCHAR(length=80),
               comment=None,
               existing_comment='Icon name or icon key.',
               existing_nullable=False)
    op.alter_column('action_types', 'color',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='Display color for the action type.',
               existing_nullable=False)
    op.alter_column('action_types', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last delete item timestamp',
               existing_nullable=True)
    op.alter_column('action_types', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('action_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Session creation timestamp.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update timestamp.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Unique message identifier.',
               existing_nullable=False)
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('chat_plant_proposals', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('chat_plant_proposals', 'image_path',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_plant_proposals_approved_plant_id'), table_name='chat_plant_proposals')
    op.drop_index(op.f('ix_chat_plant_proposals_chat_message_id'), table_name='chat_plant_proposals')
    op.drop_index(op.f('ix_chat_plant_proposals_status'), table_name='chat_plant_proposals')
    op.drop_constraint(op.f('chat_plant_proposals_chat_message_id_fkey'), 'chat_plant_proposals', type_='foreignkey')
    op.alter_column('notes', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Unique note identifier.',
               existing_nullable=False)
    op.alter_column('notes', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('notes', 'plant_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the plant.',
               existing_nullable=False)
    op.alter_column('notes', 'entry_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date of the journal entry.',
               existing_nullable=False)
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Note content.',
               existing_nullable=False)
    op.alter_column('notes', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of tags associated with the note.',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('notes', 'image_paths',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of image paths attached to the note.',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('notes', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was soft deleted.',
               existing_nullable=True)
    op.alter_column('notes', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plants', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Unique plant identifier.',
               existing_nullable=False)
    op.alter_column('plants', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('plants', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='Plant name.',
               existing_nullable=False)
    op.alter_column('plants', 'species',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='Plant species or variety name.',
               existing_nullable=False)
    op.alter_column('plants', 'potted_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date the plant was potted.',
               existing_nullable=True)
    op.alter_column('plants', 'image_path',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='Path to the plant image.',
               existing_nullable=True)
    op.alter_column('plants', 'note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='General note about the plant.',
               existing_nullable=True)
    op.alter_column('plants', 'is_paused',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indicates whether care schedules are paused.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('plants', 'overview',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='General overview of the plant.',
               existing_nullable=True)
    op.alter_column('plants', 'water',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Watering guidance.',
               existing_nullable=True)
    op.alter_column('plants', 'sunlight',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Sunlight requirement notes.',
               existing_nullable=True)
    op.alter_column('plants', 'fertilizer',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fertilizer guidance.',
               existing_nullable=True)
    op.alter_column('plants', 'propagating',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Short propagation summary.',
               existing_nullable=True)
    op.alter_column('plants', 'varieties',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Related varieties or types.',
               existing_nullable=True)
    op.alter_column('plants', 'humidity',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Humidity requirement notes.',
               existing_nullable=True)
    op.alter_column('plants', 'temperature',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Recommended temperature range.',
               existing_nullable=True)
    op.alter_column('plants', 'soil',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Soil and drainage guidance.',
               existing_nullable=True)
    op.alter_column('plants', 'running',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Growth rate and habit information.',
               existing_nullable=True)
    op.alter_column('plants', 'potting_and_repotting',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Repotting guidance.',
               existing_nullable=True)
    op.alter_column('plants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was soft deleted.',
               existing_nullable=True)
    op.alter_column('plants', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('plants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Log creation timestamp.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profile_settings', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('profile_settings', 'points',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reward points or score.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('profile_settings', 'streak_day',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Current streak count in days.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('profile_settings', 'theme',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Selected app theme.',
               existing_nullable=False,
               existing_server_default=sa.text("'LIGHT'::character varying"))
    op.alter_column('profile_settings', 'start_of_week',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='Preferred first day of the week.',
               existing_nullable=True)
    op.alter_column('profile_settings', 'device_preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON settings for device-specific preferences.',
               existing_nullable=True)
    op.alter_column('profile_settings', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was soft deleted.',
               existing_nullable=True)
    op.alter_column('profile_settings', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('profile_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profile_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Unique schedule identifier.',
               existing_nullable=False)
    op.alter_column('schedules', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('schedules', 'plant_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the plant.',
               existing_nullable=False)
    op.alter_column('schedules', 'action_type_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the action type.',
               existing_nullable=False)
    op.alter_column('schedules', 'frequency_type',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Recurrence rule type.',
               existing_nullable=False)
    op.alter_column('schedules', 'frequency_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Interval in days, if applicable.',
               existing_nullable=True)
    op.alter_column('schedules', 'days_of_week',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Selected weekdays for the schedule.',
               existing_nullable=True)
    op.alter_column('schedules', 'scheduled_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='Time of day the task is scheduled.',
               existing_nullable=False)
    op.alter_column('schedules', 'note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional note for the schedule.',
               existing_nullable=True)
    op.alter_column('schedules', 'last_completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last completion timestamp.',
               existing_nullable=True)
    op.alter_column('schedules', 'next_due_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Next due timestamp.',
               existing_nullable=True)
    op.alter_column('schedules', 'start_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date when the schedule starts.',
               existing_nullable=True)
    op.alter_column('schedules', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was soft deleted.',
               existing_nullable=True)
    op.alter_column('schedules', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_operations', 'operation_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Unique client operation key.',
               existing_nullable=False)
    op.alter_column('sync_operations', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('sync_operations', 'entity_type',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Type of entity being synced.',
               existing_nullable=False)
    op.alter_column('sync_operations', 'entity_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='ID of the affected entity, if available.',
               existing_nullable=True)
    op.alter_column('sync_operations', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Current operation status.',
               existing_nullable=False)
    op.alter_column('sync_operations', 'error',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Error details, if the operation failed.',
               existing_nullable=True)
    op.alter_column('sync_operations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Log creation timestamp.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_completions', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Unique completion record identifier.',
               existing_nullable=False)
    op.alter_column('task_completions', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('task_completions', 'schedule_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Reference to the related schedule.',
               existing_nullable=False)
    op.alter_column('task_completions', 'completion_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date the task was completed.',
               existing_nullable=False)
    op.alter_column('task_completions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Exact completion timestamp.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_completions', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was soft deleted.',
               existing_nullable=True)
    op.alter_column('task_completions', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('task_completions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_completions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('plan_tier', sa.String(length=50), server_default='free', nullable=False))
    op.add_column('users', sa.Column('revenuecat_app_user_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('revenuecat_product_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('revenuecat_store', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('revenuecat_environment', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('plan_last_event_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('plan_last_revenuecat_event_type', sa.String(length=100), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Unique identifier for the user',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='User’s email address used for login and communication.',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Hashed password stored securely for authentication.',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indicates whether the user account is enabled.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date and time when the user record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Date and time when the user record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date and time when the user record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Date and time when the user record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Indicates whether the user account is enabled.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Hashed password stored securely for authentication.',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='User’s email address used for login and communication.',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='Unique identifier for the user',
               existing_nullable=False)
    op.drop_column('users', 'plan_last_revenuecat_event_type')
    op.drop_column('users', 'plan_last_event_at')
    op.drop_column('users', 'plan_expires_at')
    op.drop_column('users', 'revenuecat_environment')
    op.drop_column('users', 'revenuecat_store')
    op.drop_column('users', 'revenuecat_product_id')
    op.drop_column('users', 'revenuecat_app_user_id')
    op.drop_column('users', 'plan_tier')
    op.alter_column('task_completions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_completions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_completions', 'version',
               existing_type=sa.INTEGER(),
               comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('task_completions', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was soft deleted.',
               existing_nullable=True)
    op.alter_column('task_completions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Exact completion timestamp.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_completions', 'completion_date',
               existing_type=sa.DATE(),
               comment='Date the task was completed.',
               existing_nullable=False)
    op.alter_column('task_completions', 'schedule_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the related schedule.',
               existing_nullable=False)
    op.alter_column('task_completions', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('task_completions', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='Unique completion record identifier.',
               existing_nullable=False)
    op.alter_column('sync_operations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Log creation timestamp.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sync_operations', 'error',
               existing_type=sa.TEXT(),
               comment='Error details, if the operation failed.',
               existing_nullable=True)
    op.alter_column('sync_operations', 'status',
               existing_type=sa.VARCHAR(length=32),
               comment='Current operation status.',
               existing_nullable=False)
    op.alter_column('sync_operations', 'entity_id',
               existing_type=sa.VARCHAR(length=36),
               comment='ID of the affected entity, if available.',
               existing_nullable=True)
    op.alter_column('sync_operations', 'entity_type',
               existing_type=sa.VARCHAR(length=64),
               comment='Type of entity being synced.',
               existing_nullable=False)
    op.alter_column('sync_operations', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('sync_operations', 'operation_id',
               existing_type=sa.VARCHAR(length=128),
               comment='Unique client operation key.',
               existing_nullable=False)
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'version',
               existing_type=sa.INTEGER(),
               comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('schedules', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was soft deleted.',
               existing_nullable=True)
    op.alter_column('schedules', 'start_date',
               existing_type=sa.DATE(),
               comment='Date when the schedule starts.',
               existing_nullable=True)
    op.alter_column('schedules', 'next_due_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Next due timestamp.',
               existing_nullable=True)
    op.alter_column('schedules', 'last_completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last completion timestamp.',
               existing_nullable=True)
    op.alter_column('schedules', 'note',
               existing_type=sa.TEXT(),
               comment='Optional note for the schedule.',
               existing_nullable=True)
    op.alter_column('schedules', 'scheduled_time',
               existing_type=postgresql.TIME(),
               comment='Time of day the task is scheduled.',
               existing_nullable=False)
    op.alter_column('schedules', 'days_of_week',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Selected weekdays for the schedule.',
               existing_nullable=True)
    op.alter_column('schedules', 'frequency_days',
               existing_type=sa.INTEGER(),
               comment='Interval in days, if applicable.',
               existing_nullable=True)
    op.alter_column('schedules', 'frequency_type',
               existing_type=sa.VARCHAR(length=32),
               comment='Recurrence rule type.',
               existing_nullable=False)
    op.alter_column('schedules', 'action_type_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the action type.',
               existing_nullable=False)
    op.alter_column('schedules', 'plant_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the plant.',
               existing_nullable=False)
    op.alter_column('schedules', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('schedules', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='Unique schedule identifier.',
               existing_nullable=False)
    op.alter_column('profile_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profile_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profile_settings', 'version',
               existing_type=sa.INTEGER(),
               comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('profile_settings', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was soft deleted.',
               existing_nullable=True)
    op.alter_column('profile_settings', 'device_preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='JSON settings for device-specific preferences.',
               existing_nullable=True)
    op.alter_column('profile_settings', 'start_of_week',
               existing_type=sa.VARCHAR(length=16),
               comment='Preferred first day of the week.',
               existing_nullable=True)
    op.alter_column('profile_settings', 'theme',
               existing_type=sa.VARCHAR(length=32),
               comment='Selected app theme.',
               existing_nullable=False,
               existing_server_default=sa.text("'LIGHT'::character varying"))
    op.alter_column('profile_settings', 'streak_day',
               existing_type=sa.INTEGER(),
               comment='Current streak count in days.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('profile_settings', 'points',
               existing_type=sa.INTEGER(),
               comment='Reward points or score.',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('profile_settings', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('plants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Log creation timestamp.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plants', 'version',
               existing_type=sa.INTEGER(),
               comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('plants', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was soft deleted.',
               existing_nullable=True)
    op.alter_column('plants', 'potting_and_repotting',
               existing_type=sa.TEXT(),
               comment='Repotting guidance.',
               existing_nullable=True)
    op.alter_column('plants', 'running',
               existing_type=sa.TEXT(),
               comment='Growth rate and habit information.',
               existing_nullable=True)
    op.alter_column('plants', 'soil',
               existing_type=sa.TEXT(),
               comment='Soil and drainage guidance.',
               existing_nullable=True)
    op.alter_column('plants', 'temperature',
               existing_type=sa.TEXT(),
               comment='Recommended temperature range.',
               existing_nullable=True)
    op.alter_column('plants', 'humidity',
               existing_type=sa.TEXT(),
               comment='Humidity requirement notes.',
               existing_nullable=True)
    op.alter_column('plants', 'varieties',
               existing_type=sa.TEXT(),
               comment='Related varieties or types.',
               existing_nullable=True)
    op.alter_column('plants', 'propagating',
               existing_type=sa.TEXT(),
               comment='Short propagation summary.',
               existing_nullable=True)
    op.alter_column('plants', 'fertilizer',
               existing_type=sa.TEXT(),
               comment='Fertilizer guidance.',
               existing_nullable=True)
    op.alter_column('plants', 'sunlight',
               existing_type=sa.TEXT(),
               comment='Sunlight requirement notes.',
               existing_nullable=True)
    op.alter_column('plants', 'water',
               existing_type=sa.TEXT(),
               comment='Watering guidance.',
               existing_nullable=True)
    op.alter_column('plants', 'overview',
               existing_type=sa.TEXT(),
               comment='General overview of the plant.',
               existing_nullable=True)
    op.alter_column('plants', 'is_paused',
               existing_type=sa.BOOLEAN(),
               comment='Indicates whether care schedules are paused.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('plants', 'note',
               existing_type=sa.TEXT(),
               comment='General note about the plant.',
               existing_nullable=True)
    op.alter_column('plants', 'image_path',
               existing_type=sa.VARCHAR(length=1024),
               comment='Path to the plant image.',
               existing_nullable=True)
    op.alter_column('plants', 'potted_date',
               existing_type=sa.DATE(),
               comment='Date the plant was potted.',
               existing_nullable=True)
    op.alter_column('plants', 'species',
               existing_type=sa.VARCHAR(length=120),
               comment='Plant species or variety name.',
               existing_nullable=False)
    op.alter_column('plants', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment='Plant name.',
               existing_nullable=False)
    op.alter_column('plants', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('plants', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='Unique plant identifier.',
               existing_nullable=False)
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was last updated.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was created.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'version',
               existing_type=sa.INTEGER(),
               comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('notes', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the record was soft deleted.',
               existing_nullable=True)
    op.alter_column('notes', 'image_paths',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of image paths attached to the note.',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('notes', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of tags associated with the note.',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('notes', 'content',
               existing_type=sa.TEXT(),
               comment='Note content.',
               existing_nullable=False)
    op.alter_column('notes', 'entry_date',
               existing_type=sa.DATE(),
               comment='Date of the journal entry.',
               existing_nullable=False)
    op.alter_column('notes', 'plant_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the plant.',
               existing_nullable=False)
    op.alter_column('notes', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('notes', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='Unique note identifier.',
               existing_nullable=False)
    op.create_foreign_key(op.f('chat_plant_proposals_chat_message_id_fkey'), 'chat_plant_proposals', 'chat_messages', ['chat_message_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_chat_plant_proposals_status'), 'chat_plant_proposals', ['status'], unique=False)
    op.create_index(op.f('ix_chat_plant_proposals_chat_message_id'), 'chat_plant_proposals', ['chat_message_id'], unique=False)
    op.create_index(op.f('ix_chat_plant_proposals_approved_plant_id'), 'chat_plant_proposals', ['approved_plant_id'], unique=False)
    op.alter_column('chat_plant_proposals', 'image_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('chat_plant_proposals', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('chat_messages', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='Unique message identifier.',
               existing_nullable=False)
    op.alter_column('action_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update timestamp.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Session creation timestamp.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('action_types', 'version',
               existing_type=sa.INTEGER(),
               comment='Sync version used for conflict handling.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('action_types', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last delete item timestamp',
               existing_nullable=True)
    op.alter_column('action_types', 'color',
               existing_type=sa.VARCHAR(length=16),
               comment='Display color for the action type.',
               existing_nullable=False)
    op.alter_column('action_types', 'icon',
               existing_type=sa.VARCHAR(length=80),
               comment='Icon name or icon key.',
               existing_nullable=False)
    op.alter_column('action_types', 'name',
               existing_type=sa.VARCHAR(length=120),
               comment='Action type name.',
               existing_nullable=False)
    op.alter_column('action_types', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Reference to the owning user.',
               existing_nullable=False)
    op.alter_column('action_types', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment='Unique action type identifier.',
               existing_nullable=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='Unique session identifier.'),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='Reference to the owning user.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Session creation timestamp.'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Last update timestamp.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('auth_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_sessions_pkey'))
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('timelines',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('plant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('timelines_plant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('timelines_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('timelines_pkey'))
    )
    op.create_index(op.f('ix_timelines_user_id'), 'timelines', ['user_id'], unique=False)
    op.create_index(op.f('ix_timelines_plant_id'), 'timelines', ['plant_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.drop_table('revenuecat_webhook_events')
    # ### end Alembic commands ###

